version: '3.8'

services:
  khacdau-backend:
    image: ${DOCKER_USERNAME}/khacdau-backend:latest
    container_name: khacdau-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8085}:${PORT:-8085}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-8085}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/khacdau_tamtin?authSource=admin&maxPoolSize=10&serverSelectionTimeoutMS=5000&socketTimeoutMS=45000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
    networks:
      - tamtin-main-network

  khacdau-frontend:
    image: ${DOCKER_USERNAME}/khacdau-frontend:latest
    container_name: khacdau-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3005}:3005"
    networks:
      - tamtin-main-network
    depends_on:
      - khacdau-backend

networks:
  tamtin-main-network:
    external: true 