version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: khac-dau-tt-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-your-secure-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-khac_dau_tt}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - khac-dau-network
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    image: ${BACKEND_IMAGE:-khac-dau-tt-backend:latest}
    container_name: khac-dau-tt-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8081
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-your-secure-password}@mongodb:27017/${MONGO_DATABASE:-khac_dau_tt}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secure-jwt-secret-change-this-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - khac-dau-network
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend
  frontend:
    image: ${FRONTEND_IMAGE:-khac-dau-tt-frontend:latest}
    container_name: khac-dau-tt-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - khac-dau-network
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local

networks:
  khac-dau-network:
    driver: bridge 